import { useState, useEffect } from 'react';
import './Home.css';
import Footer from "../components/Footer";
import Header from "../components/Header";
import { useAuthContext } from "../hooks/useAuthContext";
import { Link } from 'react-router-dom';
import { Box, Button, ButtonGroup, Card, CardHeader, Center, CardBody, CardFooter, Divider, Heading, Image, Stack, Text, Flex} from "@chakra-ui/react";
import { Link as RouterLink } from "react-router-dom";
import { ArrowForwardIcon } from '@chakra-ui/icons';


export default function Home() {
  return (
    <div className="wrapper">
    <Header />
      <Box bg="white" p={8} m={4} borderRadius="md" textAlign="center" style={{ height: '80vh', marginTop: "40px"}}>
        <Heading as="h1" size="2xl" mb={4}>Welcome</Heading>
        <Heading size="lg">
          to the Web-based Recommendation System for Scientific Conferences!
        </Heading>
        <Button rightIcon={<ArrowForwardIcon />} as={RouterLink} to="/conferences" colorScheme='messenger' variant='outline' style={{marginTop: "20px"}}>
          Explore
        </Button>
      </Box>
      <Flex bg="blue.200" p={12} border='2px' borderColor='black.200' alignItems="center" style={{ height: '100vh' }}>
        <Box style={{ width: "50%" }} >
          <Heading as="h1" size="2xl" mb={4}>What is the focus of the app?</Heading>
          <Heading>
            This app focuses on developing a web-based recommendation system for scientific conferences. Currently, there's a lack of comprehensive web applications that can manage and recommend papers to reviewers. This project aims to fill that gap.
          </Heading>
        </Box>
        <Box style={{ width: "50%" }}>
          <Image src="/images/ethereum.png" alt="Image" height="450px" />
        </Box>
      </Flex>
      <Flex bg="teal.100" p={10} border='2px' borderColor='black.100' alignItems="center" style={{ height: '100vh', bordeTop: "1px", borderWidth:"1px"}}>
        <Box style={{ width: "50%" }}>
          <Image src="/images/people.png" alt="Image" height="300px" marginLeft="100px"/>
        </Box>
        <Box style={{ width: "50%" }}>
          <Heading as="h1" size="2xl" mb={4}>What can a user do?</Heading>
          <Heading size="lg">
            The user has multiple possibilities. He can create new conferences, he can join conferences that other users have created, he can view conference that already exists and also he can review papers that already exists in conferences.
          </Heading>
        </Box>
      </Flex>
      <Flex bg="orange.100" p={14} border='2px' borderColor='black.200' alignItems="center" style={{ height: '100vh', marginBottom: '40px'}}>
        <Box style={{ width: "50%" }}>
          <Heading size="lg">
          The user has the option to receive recommendations for conference paper reviewers. Each reviewer will be matched with a minimum of three papers generated by our recommendation system.
          </Heading>
        </Box>
        <Box style={{ width: "50%" }} p={20}>
          <Image src="/images/tv_image.png" alt="Image" height="450px" />
        </Box>
      </Flex>


    <Footer />
  </div>
  );
}

// user from useAuthContext
// AuthContext {user: {…}} (console)
/* user: 
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI4ODU0N2MzZTU1NmY4ZmRkOGMyNmQiLCJpYXQiOjE2ODAzNzcxNTksImV4cCI6MTY4MDYzNjM1OX0.8lXzgC9zYaCz4-xhePZOmf04fq7K2Hn86IsimvXf2oA"
    user: 
      email: "skavvathas@gmail.com"
      firstName: "Spiros"
      lastName: "Kavvathas"
      password: "25f9e794323b453885f5181f1b624d0b"
      username: "skavvathas"
      __v: 0
      _id: "64288547c3e556f8fdd8c26d" */
// user.token for the token of the user
// user.user.firstName for the first name of the user
// use.user.username for the username
// etc
